/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PaymentsImmutables,
  PaymentsImmutablesInterface,
} from "../PaymentsImmutables";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "permit2",
            type: "address",
          },
          {
            internalType: "address",
            name: "weth9",
            type: "address",
          },
        ],
        internalType: "struct PaymentsParameters",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x60c0604052346100c157604051601f6100ea38819003918201601f19168301916001600160401b038311848410176100ad5780849260409485528339810103126100c15760408051919082016001600160401b038111838210176100ad5761007891602091604052610070816100c5565b8452016100c5565b602082018190526001600160a01b0390811660805290511660a052604051601090816100da823960805181505060a051815050f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b51906001600160a01b03821682036100c15756fe5f80fdfea164736f6c634300081a000a";

export class PaymentsImmutables__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    params: { permit2: string; weth9: string },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PaymentsImmutables> {
    return super.deploy(params, overrides || {}) as Promise<PaymentsImmutables>;
  }
  getDeployTransaction(
    params: { permit2: string; weth9: string },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(params, overrides || {});
  }
  attach(address: string): PaymentsImmutables {
    return super.attach(address) as PaymentsImmutables;
  }
  connect(signer: Signer): PaymentsImmutables__factory {
    return super.connect(signer) as PaymentsImmutables__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PaymentsImmutablesInterface {
    return new utils.Interface(_abi) as PaymentsImmutablesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PaymentsImmutables {
    return new Contract(address, _abi, signerOrProvider) as PaymentsImmutables;
  }
}
