/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ChainedActions,
  ChainedActionsInterface,
} from "../ChainedActions";

const _abi = [
  {
    inputs: [],
    name: "InsufficientETH",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientToken",
    type: "error",
  },
  {
    inputs: [],
    name: "SPOKE_POOL",
    outputs: [
      {
        internalType: "contract IV3SpokePool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ChainedActions__factory {
  static readonly abi = _abi;
  static createInterface(): ChainedActionsInterface {
    return new utils.Interface(_abi) as ChainedActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainedActions {
    return new Contract(address, _abi, signerOrProvider) as ChainedActions;
  }
}
