/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IUniversalRouterInterface extends ethers.utils.Interface {
  functions: {
    "execute(bytes,bytes[],uint256)": FunctionFragment;
    "executeSigned(bytes,bytes[],bytes32,bytes32,bool,bytes32,bytes,uint256)": FunctionFragment;
    "signedRouteContext()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSigned",
    values: [
      BytesLike,
      BytesLike[],
      BytesLike,
      BytesLike,
      boolean,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "signedRouteContext",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signedRouteContext",
    data: BytesLike
  ): Result;

  events: {};
}

export class IUniversalRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IUniversalRouterInterface;

  functions: {
    execute(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        signer: string;
        intent: string;
        data: string;
      }
    >;
  };

  execute(
    commands: BytesLike,
    inputs: BytesLike[],
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeSigned(
    commands: BytesLike,
    inputs: BytesLike[],
    intent: BytesLike,
    data: BytesLike,
    verifySender: boolean,
    nonce: BytesLike,
    signature: BytesLike,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  signedRouteContext(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & { signer: string; intent: string; data: string }
  >;

  callStatic: {
    execute(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        signer: string;
        intent: string;
        data: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    execute(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    signedRouteContext(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
