/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IV3SpokePoolInterface extends ethers.utils.Interface {
  functions: {
    "depositV3(address,address,address,address,uint256,uint256,uint256,address,uint32,uint32,uint32,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositV3",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "depositV3", data: BytesLike): Result;

  events: {};
}

export class IV3SpokePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IV3SpokePoolInterface;

  functions: {
    depositV3(
      depositor: string,
      recipient: string,
      inputToken: string,
      outputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityDeadline: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositV3(
    depositor: string,
    recipient: string,
    inputToken: string,
    outputToken: string,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    destinationChainId: BigNumberish,
    exclusiveRelayer: string,
    quoteTimestamp: BigNumberish,
    fillDeadline: BigNumberish,
    exclusivityDeadline: BigNumberish,
    message: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositV3(
      depositor: string,
      recipient: string,
      inputToken: string,
      outputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityDeadline: BigNumberish,
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    depositV3(
      depositor: string,
      recipient: string,
      inputToken: string,
      outputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityDeadline: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositV3(
      depositor: string,
      recipient: string,
      inputToken: string,
      outputToken: string,
      inputAmount: BigNumberish,
      outputAmount: BigNumberish,
      destinationChainId: BigNumberish,
      exclusiveRelayer: string,
      quoteTimestamp: BigNumberish,
      fillDeadline: BigNumberish,
      exclusivityDeadline: BigNumberish,
      message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
