/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UniversalRouterInterface extends ethers.utils.Interface {
  functions: {
    "SPOKE_POOL()": FunctionFragment;
    "V3_POSITION_MANAGER()": FunctionFragment;
    "V4_POSITION_MANAGER()": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "execute(bytes,bytes[])": FunctionFragment;
    "executeSigned(bytes,bytes[],bytes32,bytes32,bool,bytes32,bytes,uint256)": FunctionFragment;
    "msgSender()": FunctionFragment;
    "noncesUsed(address,bytes32)": FunctionFragment;
    "poolManager()": FunctionFragment;
    "signedRouteContext()": FunctionFragment;
    "uniswapV3SwapCallback(int256,int256,bytes)": FunctionFragment;
    "unlockCallback(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "SPOKE_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "V3_POSITION_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "V4_POSITION_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSigned",
    values: [
      BytesLike,
      BytesLike[],
      BytesLike,
      BytesLike,
      boolean,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "msgSender", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "noncesUsed",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signedRouteContext",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCallback",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "SPOKE_POOL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "V3_POSITION_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "V4_POSITION_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "msgSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noncesUsed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signedRouteContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCallback",
    data: BytesLike
  ): Result;

  events: {
    "EIP712DomainChanged()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
}

export type EIP712DomainChangedEvent = TypedEvent<[] & {}>;

export class UniversalRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniversalRouterInterface;

  functions: {
    SPOKE_POOL(overrides?: CallOverrides): Promise<[string]>;

    V3_POSITION_MANAGER(overrides?: CallOverrides): Promise<[string]>;

    V4_POSITION_MANAGER(overrides?: CallOverrides): Promise<[string]>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    "execute(bytes,bytes[])"(
      commands: BytesLike,
      inputs: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "execute(bytes,bytes[],uint256)"(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    msgSender(overrides?: CallOverrides): Promise<[string]>;

    noncesUsed(
      user: string,
      nonce: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean] & { used: boolean }>;

    poolManager(overrides?: CallOverrides): Promise<[string]>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        signer: string;
        intent: string;
        data: string;
      }
    >;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  SPOKE_POOL(overrides?: CallOverrides): Promise<string>;

  V3_POSITION_MANAGER(overrides?: CallOverrides): Promise<string>;

  V4_POSITION_MANAGER(overrides?: CallOverrides): Promise<string>;

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  "execute(bytes,bytes[])"(
    commands: BytesLike,
    inputs: BytesLike[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "execute(bytes,bytes[],uint256)"(
    commands: BytesLike,
    inputs: BytesLike[],
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeSigned(
    commands: BytesLike,
    inputs: BytesLike[],
    intent: BytesLike,
    data: BytesLike,
    verifySender: boolean,
    nonce: BytesLike,
    signature: BytesLike,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  msgSender(overrides?: CallOverrides): Promise<string>;

  noncesUsed(
    user: string,
    nonce: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  poolManager(overrides?: CallOverrides): Promise<string>;

  signedRouteContext(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & { signer: string; intent: string; data: string }
  >;

  uniswapV3SwapCallback(
    amount0Delta: BigNumberish,
    amount1Delta: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlockCallback(
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    SPOKE_POOL(overrides?: CallOverrides): Promise<string>;

    V3_POSITION_MANAGER(overrides?: CallOverrides): Promise<string>;

    V4_POSITION_MANAGER(overrides?: CallOverrides): Promise<string>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    "execute(bytes,bytes[])"(
      commands: BytesLike,
      inputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "execute(bytes,bytes[],uint256)"(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    msgSender(overrides?: CallOverrides): Promise<string>;

    noncesUsed(
      user: string,
      nonce: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    poolManager(overrides?: CallOverrides): Promise<string>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        signer: string;
        intent: string;
        data: string;
      }
    >;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unlockCallback(data: BytesLike, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "EIP712DomainChanged()"(): TypedEventFilter<[], {}>;

    EIP712DomainChanged(): TypedEventFilter<[], {}>;
  };

  estimateGas: {
    SPOKE_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    V3_POSITION_MANAGER(overrides?: CallOverrides): Promise<BigNumber>;

    V4_POSITION_MANAGER(overrides?: CallOverrides): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    "execute(bytes,bytes[])"(
      commands: BytesLike,
      inputs: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "execute(bytes,bytes[],uint256)"(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    msgSender(overrides?: CallOverrides): Promise<BigNumber>;

    noncesUsed(
      user: string,
      nonce: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolManager(overrides?: CallOverrides): Promise<BigNumber>;

    signedRouteContext(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    SPOKE_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    V3_POSITION_MANAGER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    V4_POSITION_MANAGER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "execute(bytes,bytes[])"(
      commands: BytesLike,
      inputs: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "execute(bytes,bytes[],uint256)"(
      commands: BytesLike,
      inputs: BytesLike[],
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeSigned(
      commands: BytesLike,
      inputs: BytesLike[],
      intent: BytesLike,
      data: BytesLike,
      verifySender: boolean,
      nonce: BytesLike,
      signature: BytesLike,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    msgSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    noncesUsed(
      user: string,
      nonce: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    signedRouteContext(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlockCallback(
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
